apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-gradle-library
  namespace: tekton
spec:
  params:
  - name: repo-url
    type: string
  workspaces:
  - name: shared-data
    persistentVolumeClaim:
      claimName: tekton-workspace
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
