apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-gradle-library-build
spec:
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "Hello World 2"  