apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-hello
  namespace: tekton-pipelines
spec:
  steps:
    - name: helloworld
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Hello World"
