apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-gradle-build
spec:
  steps:
    - name: build
      image: openjdk:17-alpine
      script: |
        #!/bin/bash
        echo "Hello World"
